const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const html = fs.readFileSync(require('node:path').join(__dirname, '../desktop_reminder.html'), 'utf8');
const nodes = {};
const get = key => nodes[key] ||= {};
const context = vm.createContext({document: {
    body: {style: {setProperty(key,value) { get('colors')[key]=value; }}, classList: {toggle() {}}}, getElementById: get, querySelector: get,
}, window: {addEventListener() {}}});
vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1], context);
const render = context.renderReminder;
render({level:'start', class_name:'2-3', text:{start_title:'어서 가요 <b>선생님</b>', button_label:'출발!'}});
assert.equal(get('.mute').hidden, true);
assert.equal(get('title').textContent, '어서 가요 <b>선생님</b>');
assert.equal(get('.primary').textContent, '출발!');
assert.equal(get('room').textContent, '2학년 3반');
render({level:'urgent', text:{urgent_title:'수업이 기다려요!'}});
assert.equal(get('.mute').hidden, false);
assert.equal(get('title').textContent, '수업이 기다려요!');
assert.equal(get('.primary').textContent, '지금 갈게요!');
render({level:'start', text:{start_title:''}});
assert.equal(get('.mute').hidden, true);
assert.equal(get('title').textContent, '수업 시작 시간이에요!');
console.log('Reminder text, defaults, and urgent-only mute passed.');

render({level:'start', text:{start_background:'#abcdef',start_foreground:'#102030'}});
assert.equal(get('colors')['--reminder-bg'], '#abcdef');
assert.equal(get('colors')['--reminder-fg'], '#102030');
render({level:'urgent', text:{urgent_background:'#001122',urgent_foreground:'#ffeedd'}});
assert.equal(get('colors')['--reminder-bg'], '#001122');
assert.equal(get('colors')['--reminder-fg'], '#ffeedd');
render({level:'start', text:{start_background:'invalid'}});
assert.equal(get('colors')['--reminder-bg'], '#eef4ff');
assert.equal(get('colors')['--reminder-fg'], '#123163');
console.log('Custom colors and invalid color fallback passed.');
const photo = 'data:image/jpeg;base64,YWJj';
assert.equal(context.reminderBackground({start_image:photo}, false), `linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),url("${photo}")`);
assert.equal(context.reminderBackground({start_image:photo}, true), 'none');
assert.equal(context.reminderBackground({urgent_image:photo,urgent_dim:0}, true), `linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)),url("${photo}")`);
assert.equal(context.reminderBackground({start_image:'https://example.com/photo.jpg'}, false), 'none');
render({level:'start',text:{start_image:photo}});
assert.notEqual(context.document.body.style.backgroundImage, 'none');
render({level:'start',text:{}});
assert.equal(context.document.body.style.backgroundImage, 'none');
const settingsHtml = fs.readFileSync(require('node:path').join(__dirname, '../settings.html'), 'utf8');
const settingsCode = settingsHtml.slice(settingsHtml.indexOf('const REMINDER_COLORS'), settingsHtml.indexOf('async function previewDesktopReminder'));
const fields = {};
const field = id => fields[id] ||= {value:'',removeAttribute(name){delete this[name];}};
const editor = vm.createContext({data:{desktop_reminder_text:{start_image:photo,start_dim:25}},document:{getElementById:field}});
vm.runInContext(settingsCode, editor);
for (const key of ['start_title','urgent_title','button_label']) field('reminder_'+key).value='custom';
editor.updateReminderText();
assert.equal(editor.data.desktop_reminder_text.start_image, photo);
assert.equal(editor.data.desktop_reminder_text.start_dim, 25);
editor.removeReminderPhoto('start');
assert.equal(editor.data.desktop_reminder_text.start_image, undefined);
assert.equal(field('reminder_start_thumbnail').hidden, true);
editor.data.desktop_reminder_text.urgent_image=photo;
editor.resetReminderText();
assert.equal(editor.data.desktop_reminder_text.urgent_image, undefined);
assert.equal(editor.data.desktop_reminder_text.start_background, '#eef4ff');
console.log('Photo background, removal, reset, and preservation during text edits passed.');
