const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const html = fs.readFileSync(require('node:path').join(__dirname, '../settings.html'), 'utf8');
const code = html.slice(html.indexOf('function onUpdateCheckResult('), html.indexOf('async function pollStartupEnabledResult('));
const elements = {'update-desc': {}, 'update-btn': {style: {}}};
const context = vm.createContext({document: {getElementById: id => elements[id]}, doInstallUpdate() {}, checkUpdate() {}});
vm.runInContext(code, context);
context.onUpdateCheckResult({has_update: true, version: '3.1.1', current: '3.1.0', url: 'installer'});
assert.equal(elements['update-btn'].disabled, false);
context.onUpdateCheckResult({has_update: false, version: '3.1.1', current: '3.1.0', other_platform_release: 'Windows'});
assert.match(elements['update-desc'].textContent, /v3.1.1.*Windows/);
assert.match(elements['update-desc'].textContent, /업데이트가 필요 없어요/);
assert.equal(elements['update-btn'].textContent, '업데이트 불필요');
assert.equal(elements['update-btn'].disabled, true);
assert.equal(elements['update-btn'].onclick, null);
assert.equal(context._updateUrl, null);
context.onUpdateCheckResult({has_update: false, version: '3.1.3', current: '3.1.2', other_platform_release: 'macOS'});
assert.match(elements['update-desc'].textContent, /v3.1.3.*macOS/);
assert.match(elements['update-desc'].textContent, /업데이트가 필요 없어요/);
assert.equal(elements['update-btn'].textContent, '업데이트 불필요');
assert.equal(elements['update-btn'].disabled, true);
assert.equal(context._updateUrl, null);
context.onUpdateCheckResult({error: 'offline'});
assert.equal(elements['update-btn'].textContent, '재시도');
assert.equal(elements['update-btn'].disabled, false);
console.log('Platform-specific release notice and retry behavior passed.');
